routes/web.php
<?php

use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\StudentClassController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\MarkImportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('subjects', SubjectController::class);
Route::resource('students', StudentController::class);
Route::get('total', [StudentController::class, 'student'])->name('student.total');
Route::get('totalstudent/{id}', [StudentController::class, 'total'])->name('student.totalclass');
Route::resource('results', ResultController::class);
Route::get('getclassid/{id}',[ResultController::class, 'getClassId']);
Route::resource('classes', StudentClassController::class);
Route::resource('imports', StudentImportController::class);
Route::resource('markimports', MarkImportController::class);
Route::get('classresult/{id}', [ResultController::class, 'classresult']);
Route::get('pdfview/{id}',array('as'=>'pdfview','uses'=>'App\Http\Controllers\ResultController@pdfview'));

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('page_title')</title>
    <meta name="author" content="David Grzyb">
    <meta name="description" content="">

    <!-- Tailwind -->
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js" type="text/javascript"></script>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Karla:400,700&display=swap');
        .font-family-karla { font-family: karla; }
        .bg-sidebar { background: #ff0000; }
        .cta-btn { color: #ff0000; }
        .upgrade-btn { background: #fd3300; }
        .upgrade-btn:hover { background: #dd0101; }
        .active-nav-link { background: #ee1919; }
        .nav-item:hover { background: #ee1919; }
        .account-link:hover { background: #ff0000; }
    </style>
</head>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

<body class="bg-gray-100 font-family-karla flex">

    <aside class="relative bg-sidebar h-screen w-64 hidden sm:block shadow-xl">
        <nav class="text-white text-base font-semibold pt-3">
            <a href="{{ route('classes.index') }}" class="flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-tachometer-alt mr-3"></i>
                Class List
            </a>
            <a href="{{ route('subjects.index') }}" class="flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <i class="fas fa-tachometer-alt mr-3"></i>
                Subject List
            </a>
            <div @click.away="open = false" class="flex flex-col w-full md:w-64 text-gray-700 bg-blue dark-mode:text-gray-200 dark-mode:bg-gray-800 flex-shrink-0 "  x-data="{ open: false }">
                <button @click="open = !open" class="flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <span>
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    Student List
                </span>
                <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </button>
                <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg">
                <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
                    <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('students.index') }}">Student's List</a>
                    <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('imports.create') }}">Import Student</a>
                    <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('student.total') }}">Total Student</a>
                </div>
            </div>
            <div @click.away="open = false" class="flex flex-col w-full md:w-64 text-gray-700 bg-blue dark-mode:text-gray-200 dark-mode:bg-gray-800 flex-shrink-0 "  x-data="{ open: false }">
                <button @click="open = !open" class="flex items-center text-white opacity-75 hover:opacity-100 py-4 pl-6 nav-item">
                <span>
                    <i class="fas fa-tachometer-alt mr-3"></i>
                    Result Sheet
                </span>
                <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </button>
                <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg">
                <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
                    <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('results.index') }}">View Sheet</a>
                    <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{{ route('markimports.create') }}">Import sheet</a>
                </div>
            </div>
        </nav>
    </aside>

    <div class="relative w-full flex flex-col h-screen overflow-y-hidden">
        {{-- messages --}}
        @if (session('SUCCESS'))
                <div class="m-4 px-4 py-2 text-center border border-green-600 bg-green-200 text-green-800">
                    {{ session('SUCCESS') }}
                </div>
        @endif

        @if (session('ERROR'))
            <div class="m-4 px-4 py-2 text-center border border-red-600 bg-red-200 text-red-800">
                {{ session('ERROR') }}
            </div>
        @endif

        @if (isset($errors) && $errors->any())
            <div class="m-4 px-4 py-2 text-center border border-red-600 bg-red-200 text-red-800">
                @foreach ($errors->all() as $error)
                    {{ $error }}
                @endforeach
                </div>
        @endif

        @if (session()->has('failures'))
            <table class="m-4 px-4 py-2 text-center border border-red-600 bg-red-200 text-red-800">
            <tr>
                <td>Row</td>
                <td>Attributes</td>
                <td>Errors</td>
                <td>Value</td>
            </tr>
            @foreach (session()->get('failures') as $validation)
            <tr>
                <td>{{ $validation->row() }}</td>
                <td>{{ $validation->attribute() }}</td>
                <td>
                    <ul>
                        @foreach ($validation->errors() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </td>
                {{-- <td>{{ $validation->values()[$validation->attribute()] }}</td> --}}
            </tr>
            @endforeach
            </table>
        @endif
        @yield('content')
    </div>

    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    {{-- jquery --}}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>